import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/styles/global.scss'
import ThemeProvider from '@/context/ThemeProvider'
import StoreProvider from '@/redux/StoreProvider'
import ThemeToggle from '@/context/ThemeProvider/ThemeToggle'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="vi">
      <body>
        <StoreProvider>
          <ThemeProvider>
            {children}
            <ThemeToggle
              className="fixed bottom-4 left-4 z-50 hidden md:flex"
              buttonProps={{
                className: 'dark:bg-gray-800 bg-white shadow-mprimary',
              }}
            />
          </ThemeProvider>
        </StoreProvider>
      </body>
    </html>
  )
}
